### PR TITLE
TASK: Adding infinite loop animation to logo bar & randomize order

### PR DESCRIPTION
**Pull request by rtp-cgs**

### CODE REVIEW

**Comment by manuelmeister** [comment]
Looks good. I think this is better suited in Molecules.

**Review by manuelmeister — CHANGES_REQUESTED** [review]
Could you move this to molecules and extract the scripts to an external .ts file?

**Comment by rtp-cgs** [comment]
I moved the component to the molecules folder and the inline js to a separate file.

**Comment by jonnitto** [comment]
```js
import Alpine from 'alpinejs';

Alpine.data('LogoBar', () => ({
    init() {
         const logos = this.$refs.logos;
         logos.replaceChildren(...[...logos.children].sort(() => Math.random() - 0.5));
         this.$nextTick(() => {
             for (let i = 1; i <= 3; i++) {
                 logos.insertAdjacentHTML('afterend', logos.outerHTML);
                 logos.nextSibling.setAttribute('aria-hidden', 'true');
             }
         });
     },
}));
```

**Review by jonnitto — APPROVED** [review]

**Pull request merged**
