### PR TITLE
FEATURE: Add Discourse connector plugin

### PR DESCRIPTION
**Pull request by kdambekalns**
Adds the plugin and configures it a tad bit.

### CODE REVIEW

**Comment by kdambekalns** [comment]
This is how it looks like, pulling in three lists, the lower two are the same category, once showing only open, once only closed topics.

topic-lists

**Comment by dfeyer** [comment]
Really awesome, no time to test it today, but look like a nice intergration

**Comment by kdambekalns** [comment]
Well, thanks! It's very, very basic so far. Have some more ideas. And an editor that allows to search for categories instead of having to configure an id would be nice. And… ;)

**Comment by bwaidelich** [comment]
Sweet! (by reading)

**Pull request merged**
