### PR TITLE
TASK: Update Neos 2.2.3 + MarketPlace 0.1.10

### PR DESCRIPTION
**Pull request by dfeyer**
Don't forget to test the package repository (performance improvements):

    flow marketplace:sync --force
    flow nodeindex:build

See https://github.com/neos/Neos.MarketPlace/pull/15 for more details

### CODE REVIEW

**Comment by kdambekalns** [comment]
Hah, a trivial change to one file, what could possibly go wrong? ;) I'll give that a try, if possible. Does it work (in a testable state) if I import the site from the repo? Or does it need the state from the live server?

**Comment by johannessteu** [comment]
Hey @dfeyer ,

i just installed it and hat a quick look. Performance wise 👍 But need to test more. But what about this:

The latest version seems not be set correctly?!

screen shot 2016-05-20 at 19 30 09
screen shot 2016-05-20 at 19 30 15

Didn't hat time to look into the code yet

**Comment by johannessteu** [comment]
There are also some packages with no version at all like the flow-dev-collection. If you click those you run into an exception 
 
screen shot 2016-05-20 at 19 33 25
screen shot 2016-05-20 at 19 34 15

Sorry for only providing screenshots, i'm a bit on a hurry atm. Will be back online later

**Comment by dfeyer** [comment]
Thanks @johannessteu for the review, will check both issue right now

**Comment by dfeyer** [comment]
Merge ready from my side

**Comment by kdambekalns** [comment]
I can at least confirm the update works "basically", as far as I could test that locally without a current dump of the live content. Anyway, it synced the packages and `nodeindex:build` worked as well. So, if you say it is ready, it is ready. I guess. :)

**Comment by johannessteu** [comment]
i tested everything locally, but did not looked at the code. But merge ready also from my side!

**Comment by dfeyer** [comment]
Last few commit for the PR, mainly cleanup the JS build by merging the JS of the site and the marketplace, and improve styling of the Version Navigation.

Feel free to hit the button, not sure it the automatic deployment is in place ;) so it's not the perfect time to kill the production website ;)

**Comment by bwaidelich** [comment]
Just in case you weren't aware: This change updates the following packages to a new patchlevel version:
```knplabs/github-api, neos/composer-plugin, symfony/console, symfony/event-dispatcher, zendframework/zend-code, phpunit/php-timer, sebastian/environment, neos/*, typo3/*```
and ```symfony/polyfill-mbstring``` to a new *minor* version

**Comment by dfeyer** [comment]
@bwaidelich The title is too short to have the full list of package, but all this is part of **Update Neos 2.2.3**

**Comment by bwaidelich** [comment]
@dfeyer Ah, right. I missed the subject line

**Pull request merged**
