### PR TITLE
FEATURE: Teams plugin

### PR DESCRIPTION
**Pull request by Sebobo**
This plugin can be used to show either teams or guilds.
Each group will show all it's members.
Each member can be clicked to show details in a modal.

Also provided are several commands for modifying and listing
groups and users from crowd.
Groups which should appear need to have the
property `neos_group_type` set to `team` or `guild`.

### CODE REVIEW

**Comment by mgoldbeck** [comment]
:+1:  But you said something about writing Readme ;)

**Comment by dfeyer** [comment]
Really target to master ? And not to the new branch ?

**Comment by Sebobo** [comment]
@mgoldbeck the readme just magically appeared ;)

@dfeyer yes as we started some time ago it's build for the old site and not yet
modified for the new one. And this way we can already experiment with it and improve it 
when we adapt the plugin for the new site.
Anyway the crowd integration and funding should move into separate packages which would
make things easier.

**Comment by mgoldbeck** [comment]
:+1:

**Pull request merged**
