### PR TITLE
Update to Neos 5.3

### PR DESCRIPTION
**Pull request by kdambekalns**
Updates the setup from Neos 4.3 to 5.3 and makes it work with Elasticsearch 7.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Setup compiles and Neos basically works. Still to do:

- Elasticsearch 6 adjustments
- PSR-7 adjustments
- Fusion fixes (a lot of `No template path set.`)
- … probably more things

**Comment by kdambekalns** [comment]
While running `marketplace:sync`:

```
{
    "update": {
        "_index": "wwwneosio-e781f29c8dd927c09735547a848e3459",
        "_type": "_doc",
        "_id": "e152121a11826bf9c621a62a75c11b65fc2ecb1d",
        "status": 400,
        "error": {
            "type": "illegal_argument_exception",
            "reason": "Limit of total fields [1000] in index [wwwneosio-e781f29c8dd927c09735547a848e3459] has been exceeded"
        }
    }
}
```

**Comment by kdambekalns** [comment]
Ok, the site(s) run more or less, see https://instance-3212ded4-17fc-4a33-bebe-cc8ba4ec01c6.flownative.cloud/ That is only showing the neos.io site, Flow and Conference are not available (too lazy to create subdomains for the staging instance.) And the resources are missing to some degree, hence the black boxes where you'd expect images. But worth clicking around a bit…

But the Neos.MarketPlace is still buggy. Not surprising given it must be updated to Elasticsearch v6.

- In https://github.com/neos/Neos.NeosIo/pull/373/files#diff-be643105d46a341fc4ddc0c9400f1894ae649c65275ff9c1e10f589a69386ce1R144 an object field is queried that does not exist after indexing - when commented out, no errors appear…
- listing all indexed packages gives an empty result. I fed the query JSON into Elasticsearch and got 0 results, but have no clue why the query doies not work.
- searching actually shows results, even though sometimes the display is weird, showing more than just packages but what seems to be misrendered package version hits
- counting results is very much incorrect
- indexing everything runs into memory issues

It would be great to get some help with that, maybe even from Mr. Search (@daniellienert) himself. 😎

**Comment by markusguenther** [comment]
Awesome work Karsten. Thanks for that and the you step in.
Clicked bit around and it seems to work fine except the image teasers. The are not linked anymore.

Even the service provider listing is working :)

Screenshot 2020-11-25 at 12 01 37

**Comment by kdambekalns** [comment]
> except the image teasers. They are not linked anymore.

Should work now…

**Comment by regniets** [comment]
Thanks @kdambekalns! Seems like the only issue left is the MarketPlace?

**Comment by kdambekalns** [comment]
Exactly, as I wrote in https://github.com/neos/Neos.NeosIo/pull/373#issuecomment-733287579 20(!) days ago… 😱

With lots of work and the release in between I did not gte around to digging any further, but as said already, I'd need help with the ES stuff anyways.

**Comment by regniets** [comment]
ok, just wanted to check if anything has happened in between. I will check into it and see if i can find something. Do you know how much time is left approx. for the existing ES support?

**Comment by kdambekalns** [comment]
> Do you know how much time is left approx. for the existing ES support?

How long it will still be hosted? About minus 4 weeks by now… ;)

**Comment by regniets** [comment]
ok, thanks.

**Comment by regniets** [comment]
Hi @kdambekalns, i checked into the ES queries and got it running at least.
Would be terrific if @daniellienert could take a look at some point...

**Comment by regniets** [comment]
I did a test with backstopjs between live and staging - there are a few little errors with some of the fluid based nodeTypes (e.g. background color of content stage not working). Since i dont want to introduce more code change than neccessary with moving them to afx, i will put in the good old generators where neccessary.

Other than that the main issue remains indexing (marketplace:sync) which runs out of memory.

**Comment by regniets** [comment]
With the latest commits (and some elasticsearch index cleanup), `nodeindex:build` is working again.
Now `marketplace:sync` seems to run into the following exception which causes the massive delay  and memory outage (at least locally where i got the Exception in Development.log because not catched otherwise):

`Exception in line 3460 of /application/Packages/Libraries/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php: A new entity was found through the relationship 'Neos\ContentRepository\Domain\Model\NodeData#workspace' that was not configured to cascade persist operations for entity: Neos\ContentRepository\Domain\Model\Workspace@000000004511d53c0000000075f9e001. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Neos\ContentRepository\Domain\Model\Workspace#__toString()' to get a clue.`

@kdambekalns - any clue? 
See also here: https://github.com/neos/neos-development-collection/issues/3280

**Comment by kdambekalns** [comment]
Continuing with this…

# Mapping explosion

As described in https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/issues/375 I saw this. Adding the workaround (setting type to `flattened` and unsetting `enabled`) didn't help… until I created the mapping using `./flow nodeindex:build --workspace live --limit 1` instead of just starting `marketplace:sync`.

# Empty package list

The mapping issue described above also caused the path and parent path fields to be indexed as `text` instead of `keyword`, leading to no packages in the list, because the filter on the node path never matches.

# Immense term in field="source"

That's an interesting one…

```json
{
    "index": {
        "_index": "wwwneosio-e781f29c8dd927c09735547a848e3459-1627635792",
        "_type": "_doc",
        "_id": "1849a84221ae3bae8b8775c44283655bac331779",
        "status": 400,
        "error": {
            "type": "illegal_argument_exception",
            "reason": "Document contains at least one immense term in field=\"source\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[60, 112, 62, 60, 97, 32, 104, 114, 101, 102, 61, 34, 104, 116, 116, 112, 58, 47, 47, 111, 112, 101, 110, 115, 111, 117, 114, 99, 101, 46]...', original message: bytes can be at most 32766 in length; got 41243",
            "caused_by": {
                "type": "max_bytes_length_exceeded_exception",
                "reason": "bytes can be at most 32766 in length; got 41243"
            }
        }
    }
}
```

That field is from `Neos.MarketPlace:Readme`, and some packages have rather extensive documentation. The solution could be to change the type or limit the lebgth of the reults during indexing. Whether that is best done in `Neos.MarketPlace:Readme` or in `Neos.MarketPlace:Package` (where this is indexed, too, into `__readme`) needs to be seen.

# New Workspace entity

The exception `A new entity was found through the relationship 'Neos\ContentRepository\Domain\Model\NodeData#workspace' that was not configured to cascade persist operations for entity: Neos\ContentRepository\Domain\Model\Workspace@000000002e6521f0000000005f5ad830` is still an issue. It happens as soon as the "memory limiting workaround` has been executed once:

https://github.com/neos/Neos.NeosIo/blob/b80a4de2055f540f6748f92d3f0e6f8a092c1f6d/DistributionPackages/Neos.MarketPlace/Classes/Command/MarketPlaceCommandController.php#L96-L99

Through debugging I verified the actual Workspace instance is the same across those calls (working first and then failing) and actually the one from the database. There must be some place the workspace is held in memory across clearing the UoW and the 1st level node cache.

**Comment by regniets** [comment]
@kdambekalns - Thanks for digging deeper into that.
What i found out is that the workspace issue only appears when the importer is trying to add new nodes created from a NodeTemplate - not when updating existing ones (i.e. especially when adding new versions because that happens most often).
It seems to happen exactly at this point:
https://github.com/neos/neos-development-collection/blob/5.3/Neos.ContentRepository/Classes/Domain/Model/NodeData.php#L482

**Comment by kdambekalns** [comment]
- [x] Mapping explosion - fixed with settings change, when mapping is correctly set up[1]
- [x] Empty package list - fixed when mapping is correctly set up[1]
- [x] Immense term in field="source" - fixed by mapping change
- [ ] New Workspace entity

[1] The mapping needs to be set up manually using `nodeindex:build` as described above – I tried to come up with a coding fix, but that seems to become a rather big change…

**Comment by kdambekalns** [comment]
Oh my…

`[02-Aug-2021 14:49:12 UTC] PHP Fatal error:  Allowed memory size of 786432000 bytes exhausted (tried to allocate 20480 bytes) in /application/Packages/Libraries/neos/cache/Classes/Frontend/VariableFrontend.php on line 94
`

after 16 packages…

**Comment by regniets** [comment]
poooh. 
Problem i had (which should be fixed on staging though): 
My last commit (8861a91) fixed the issue that the importer would add a whole lot of new childnodes (i.e. versions) because it did not recognize old ones (strict check), deleted them and added new ones which in turn caused the out of memory issue.
If you still work on non-usable data (node names of versions are `node-abc1234` instead of `2.1.2`) this could be the reason.

**Comment by kdambekalns** [comment]
@regniets Thanks, but your fix is in the codebase and I have no old nodes in place. In fact I don't have _any_ nodes in the storage subtree. Trying the sync on a current dump now–if that works I'd ignore the problem with indexing from scratch… for now.

**Comment by kdambekalns** [comment]
Ok, with a current dump a simpl `marketplace:sync` finishes fine and takes about 23 minutens on my machine. I'll try a `marketplace:sync --force` now for good measure.

**Comment by regniets** [comment]
What helped in my case was to remove the "memory limiting workaround" you mentioned above - because this actually has the opposite effect when creating too many nodes and not persisting in between.

**Comment by regniets** [comment]
Regarding the `nodeindex:build`: We are still performing a runtime index here:
https://github.com/neos/Neos.NeosIo/blob/update-neos5/DistributionPackages/Neos.MarketPlace/Classes/Service/PackageConverter.php#L164

Shouldn't that be removed as well? Might also speed up the import...

**Comment by kdambekalns** [comment]
- [x] Out of memory issues (solved "good enough")

A full `--force` sync on existing nodes took about 33 minutes on my machine and finished without errors. The indexing is fine now, too (showing the same total in the frontend as package nodes exist in the CR).

I'd say this can be reviewed in earnest now. The staging instance has seen a fresh Marketplace sync, but previous reviews showed only Marketplace issues were left.

I'd love to merge this into master as soon as possible now, it has been in the making for way too long…

**Comment by regniets** [comment]
Thank you so much @kdambekalns!!!
Seen my last comment on indexing?

I'd love to review this and write you on slack for details.

**Comment by kdambekalns** [comment]
@regniets Not sure about the indexing call. If we leave it out, no indexing will be done AFAICT, so why do you think that is an option?

**Comment by regniets** [comment]
@kdambekalns - we have realtime indexing enabled and as far as i remember it did index the node twice (but not 100% sure). Can you check that?

**Comment by kdambekalns** [comment]
Ok, I didn't know that's enabled (since we don't use Elasticsearch for anything, AFAIK) and thus assumed the explicit indexing is needed. I'll start a test run now…

**Comment by kdambekalns** [comment]
Works fine without the explicit indexing, no influence on the time a full sync using `--force` takes.

**Comment by regniets** [comment]
Thanks for checking into and fixing :) Well, at least we might save some CPU load ...

**Pull request merged**
