### PR TITLE
TASK: Minify static images

### PR DESCRIPTION
**Pull request by jrenggli**

### CODE REVIEW

**Comment by jrenggli** [comment]
Thanks to a 512kbit/s connection in a hotel (not mentioned by name) near the Inspiring Conference you have the perfect environment to do some performance testing. Transfer times higher than 30 seconds for just one image is definitely too much.

I'm aware that the static inclusion of these images is probably just temporary. But it would be good to optimize filesize at least a bit.

**Comment by daniellienert** [comment]
Great!

**Comment by daniellienert** [comment]
Hey @jrenggli - the new branch has been deleted. Would you mind to open the PR again against master? That would be great!

**Comment by jrenggli** [comment]
Hey @daniellienert: Just created the PR again. See #97

**Pull request closed without merging**
