### PR TITLE
TASK: Update to Neos 4.1

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
Note this needs:

- https://github.com/ttreeagency/OutOfBandRendering/pull/1
- https://github.com/neos/Neos.MarketPlace/pull/32

The composer lock file and manifest pull them in right now, but they need to be merged and the "original" used again.

Also, a new Neos release is needed to have https://github.com/neos/neos-development-collection/pull/2262 actually in.

**Comment by kdambekalns** [comment]
I checked the Neos, Flow and Conference sites and all work fine, AFAICT.

**Comment by Sebobo** [comment]
Fighting a bit with my environment then I can review

**Comment by kdambekalns** [comment]
Fixed version switching in the marktplace… please check that (see https://github.com/ttreeagency/OutOfBandRendering/pull/2 as well)

**Pull request merged**
