### PR TITLE
TASK: Initial setup for the rough new structural design and NodeTypes

### PR DESCRIPTION
**Pull request by Inkdpixels**

### CODE REVIEW

**Comment by Inkdpixels** [comment]
One question is still open for me, there is an automatic deployment in place, at least @robertlemke had told me this at some point. 

I've removed the generated `.css` and `.js`files from the respository, thus accepting this PR would break the new.neos.io site since no assets are present. So my question would be, is there any way to add some commands for the deployment to build the assets like in surf with the `defineTask` method? 

The commands to execute would be `npm install && npm run build`.

**Comment by robertlemke** [comment]
Travis would be nice!

Regarding the build process: I'll integrate that into our build, but I think it won't happen this week. Feel free to commit built css/js for the time being.

**Comment by Inkdpixels** [comment]
Done, ping me if you have some spare time for this :) :+1:

**Comment by kdambekalns** [comment]
Just tried this, but I am a bit afraid to merge it… The homepage looks great, but the other pages have no footer and a rather weird looking header. Admittedly I did not have the current database state from new.neos.io, so maybe that would work better.

**Comment by Inkdpixels** [comment]
@kdambekalns Thanks for checking! :) I've added two commits which fix the appearance of the default page NodeType template and the semantics for the Quote NodeType.

**Comment by kdambekalns** [comment]
Way better now. Thanks!

**Pull request merged**
