### PR TITLE
TASK: exclude built assets

### PR DESCRIPTION
**Pull request by Sebobo**

### CODE REVIEW

**Comment by Sebobo** [comment]
Hi @robertlemke,

any update on this?

**Comment by jonnitto** [comment]
Hi @kdambekalns 
Is it planned to add this kind of functionality into beach? 🏖 🏝 
If no, we can close this PR

**Comment by kdambekalns** [comment]
Sorry, can't remember what exactly was the blocker here… I hope @robertlemke remembers (once the conference is over)

**Comment by beheist** [comment]
@kdambekalns the blocker is probably that we'd need to run an npm command after the deployment. Didn't you say you could customize an entrypoint for beach containers that gets run after the container is deployed? This could be done in there probably.

**Comment by kdambekalns** [comment]
Yes, such a script can be run. I'm not sure about making node & friends available. They are not available out of the box (for a number of reasons). But thanks, now I know what's this about…

**Comment by Sebobo** [comment]
I drop this and add the needed gitignores to the Neos 4.3 update. The other changes are not needed anymore as the build step now works fine.

**Pull request closed without merging**
