### PR TITLE
FIX: stupidtable requires jQuery

### PR DESCRIPTION
**Pull request by Sebobo**

### CODE REVIEW

**Comment by robertlemke** [comment]
I don't know the context really, so, what does it fix and how can I test it?

**Comment by Sebobo** [comment]
All the javascripts on the site failed when you opened neos.io without being logged into the backend.
So checking the error console and the pages with the funding plugin and the sorting of the "projects" tables where the stupidtable plugin is used.

**Comment by mgoldbeck** [comment]
:+1:

**Comment by robertlemke** [comment]
Deployed to production.

**Pull request merged**
