### PR TITLE
TASK: Lazyload animated gifs

### PR DESCRIPTION
**Pull request by bwaidelich**
Work in progress..

TODO:
Replace teaser image with image from `data-original-image` attribute on click (via javascript)

Resolves: #112

### CODE REVIEW

**Comment by kdambekalns** [comment]
Yay! Looking forward to this. And IMHO another example how nicely Neos can be extended… 👍

**Comment by kdambekalns** [comment]
@bwaidelich – should this be closed in favour of #125 or is it something else?

**Comment by bwaidelich** [comment]
> should this be closed in favour of #125 or is it something else?

It's not exactly the same but yeah, I'll close it for now.. If someone needs this feature you know where to find it ;)

**Comment by aertmann** [comment]
well the `Gif.extractFirstFrame` was actually pretty neat, maybe @Sebobo would be interested in adding that to the stuff he did instead of the loading svg?

**Comment by Sebobo** [comment]
True, should be great to combine if we make the "loader" icon configurable and use the frame.

**Pull request closed without merging**
